### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by ehubbell** [rwwagner90/ember-shepherd#29]
Hi There,

Per the instructions, I just ran `ember install ember-shepherd` then `ember s` to recompile the app. When I do this, the app fails to load and my console is spitting out the following error `application.inject is not a function`. Do I need to perform additional configuration to get the app up and running? We're running on Ember 1.13 and Ember-Cli 0.2.7.

Thanks,
Eric

**Comment by rwwagner90** [comment]
Hi @ehubbell. I believe it may only work with Ember 2.0+ now. I fixed some deprecations, including some stuff with initializers.

@bekzod if we removed initializers, as you suggested, would the app work with 1.13 you think?

**Comment by bekzod** [comment]
@rwwagner90 if you fixed it, I think that will be breaking change for 1.13 users.
I don't really know if `refactor` branch works on 1.13 but 99% sure that it should :)

**Comment by rwwagner90** [comment]
@bekzod I think we should use ember try to check and see what the earliest version of ember is that will work. I'll work on that later.

**Comment by ehubbell** [comment]
Thanks for the update. We’re in the process of updating to Ember 2.0. We’ll try again when we’re complete. Meantime, let me know if I can help via testing on our 1.13 env. 


On Jan 6, 2016, at 10:10 AM, Robert Wagner <notifications@github.com> wrote:

@bekzod <https://github.com/bekzod> I think we should use ember try to check and see what the earliest version of ember is that will work. I'll work on that later.

**Comment by rwwagner90** [comment]
@ehubbell I just merged @bekzod 's changes in, which removed initializers, and may make things work again for you. We have not written up a changelog or updated the README yet, so be aware things like `trigger('start')` no longer work and you should just call `start()` etc etc

**Comment by rwwagner90** [comment]
So please try 1.1.0 and see if it works for you :smile:

**Comment by rwwagner90** [comment]
@ehubbell please confirm at your earliest convenience.

**Comment by rwwagner90** [comment]
@ehubbell everything working for you now?

**Comment by ehubbell** [comment]
Hi Robert,

So sorry I haven’t been in touch. I haven’t had a chance to integrate this. We’re in the midst of converting our staging environment and upgrading to Ember 2.0. I’ll give it a try later tonight and let you know. 

Eric



On Jan 19, 2016, at 8:49 AM, Robert Wagner <notifications@github.com> wrote:

@ehubbell <https://github.com/ehubbell> everything working for you now?

**Comment by rwwagner90** [comment]
No worries @ehubbell. Just let me know. Good luck with Ember 2.0!
